Add files via upload
r-Techsupport/rTS_Wiki pull request #165
Opened 2023-02-03 09:45 UTC by TheKrol

Uploading for Tomator Fixes #32

2023-02-03 11:20 UTC, K97i commented
> The Network Centere 👀

2023-02-05 13:44 UTC, Tomat0r commented
> > The Network Centere 👀

Most ungodly place there is

2023-02-05 15:00 UTC, K97i requested changes

2023-02-05 15:00 UTC, K97i commented on docs/guides/creating-a-smb-share.md
> +nav_order: false
Remove `nav_order: false` so that the wiki doesn't crash

2023-02-05 15:00 UTC, K97i commented on docs/guides/creating-a-smb-share.md
> +parent: Guides
`parent: General Guides`

2023-02-05 15:00 UTC, K97i commented on docs/guides/creating-a-smb-share.md
> +## The Network Centere
you can't choose both the american and british spelling choose one
`## The Network Center`
`## The Network Centre`

2023-03-09 21:37 UTC, merged