Revert DNS Settings
r-Techsupport/rTS_Wiki pull request #166
Opened 2023-02-03 13:08 UTC by K97i

closes #157

2023-02-03 13:09 UTC, Tomat0r commented
[dns.md](https://github.com/r-Techsupport/rTS_Wiki/files/10579123/dns.md)

2023-02-03 13:15 UTC, K97i commented
@Tomat0r the pull request shows the changes between the two repositories under the files changed tab so you dont have to upload the raw markdown file

![image](https://user-images.githubusercontent.com/105120272/216612415-cb3bbd6f-cb62-41ea-830f-30a299859c9c.png)

2023-02-03 13:38 UTC, TheKrol commented
Maybe update to link to terms?

2023-02-03 13:47 UTC, K97i reviewed
dns.md
add
`{: .no_toc}`
`{% include toc.md %}`
to AFTER `# Understanding DNS and How` and before `## What is DNS?`

instead of `6. Select "Use the following DNS server addresses" and enter the preferred DNS server addresses for the provider you want to use (e.g. Google's DNS servers are 8.8.8.8 and 8.8.4.4, Cloudflare's are 1.1.1.1 and 1.0.0.1, and OpenDNS's are 208.67.222.222 and 208.67.220.220).`

use `6. Select "Use the following DNS server addresses" and enter the preferred DNS server addresses for the provider [you want to use](#list-of-dns-providers)` replace all of them

2023-02-03 13:56 UTC, TheKrol requested changes
Made a PR to Tomator for DNS changes

2023-02-03 15:09 UTC, WhiteHusky requested changes
Various suggestions.

Also it might be a good idea to mention `/etc/crypttab` and how it's used to help facilitate mounting LUKS protected file systems at boot. Maybe even LVM since it's sometimes better to have one LUKS block device holding a LVM for multiple file systems.

2023-02-03 15:09 UTC, WhiteHusky commented on docs/networking/dns.md
> +The specific steps to change the DNS server in Linux depend on the distribution you are using. For most distributions, you can change the DNS server by editing the `/etc/resolv.conf` file and adding
Editing `/etc/resolv.conf` isn't advisable on distros using the `NetworkManager` or `systemd-resolved` service as both will modify `/etc/resolv.conf` themselves.

Use the GUI, or `nmcli` or `resolvectl` if you know what you are doing. It might be wise to edit/add files in `/etc/netplan/` or `/etc/network/interfaces.d/` depending on what's available.

2023-02-03 15:09 UTC, WhiteHusky commented on docs/safety-security/disk-encryption.md
> +- Not as widely used as other disk encryption software, meaning there may be less support and resources available
`cryptsetup` supports VeraCrypt. See #163

2023-02-03 15:09 UTC, WhiteHusky commented on docs/safety-security/disk-encryption.md
> +- LUKS encryption can slow down disk access speeds.
This is an unusual mention. Checking online seems to find that this is a common trend with full disk encryption, but some solutions are faster than others. LUKS at least provides some tweakables and different algorithms to work with (`cryptsetup benchmark`.) In fact VeraCrypt has an [active issue](https://github.com/veracrypt/VeraCrypt/issues/136) regarding bad performance.

Some discourse [here](https://forum.manjaro.org/t/luks-makes-ssd-slow/89114/7).

2023-02-03 15:09 UTC, WhiteHusky commented on docs/safety-security/disk-encryption.md
> +
Excessive newlines.

2023-02-03 15:09 UTC, WhiteHusky commented on docs/safety-security/disk-encryption.md
> +### It is not possible to Decrypt BitLocker without them and we will not asisst in doing so.
Would it make sense to use `>` instead of a header?

2023-02-03 15:14 UTC, WhiteHusky commented on docs/networking/dns.md
> +The specific steps to change the DNS server in Linux depend on the distribution you are using. For most distributions, you can change the DNS server by editing the `/etc/resolv.conf` file and adding
[`systemd-resolved`](https://wiki.archlinux.org/title/Systemd-networkd) can be configured by hand or via [`netplan`](https://netplan.readthedocs.io/en/latest/).

2023-02-03 16:10 UTC, sealsrock12 commented on docs/safety-security/disk-encryption.md
> +### It is not possible to Decrypt BitLocker without them and we will not asisst in doing so.
I agree with you, headings should be for sections. You can change it to
```md
> **It is not possible to Decrypt BitLocker without them and we will not asisst in doing so.**
```
or 
```md
**It is not possible to Decrypt BitLocker without them and we will not asisst in doing so.**
```

2023-02-03 16:27 UTC, Tomat0r commented on docs/safety-security/disk-encryption.md
> +### It is not possible to Decrypt BitLocker without them and we will not asisst in doing so.
Still figuring out how they work. Was aware * Exitsted but not the other things showed.

2023-02-03 16:33 UTC, WhiteHusky commented on docs/safety-security/disk-encryption.md
> +### It is not possible to Decrypt BitLocker without them and we will not asisst in doing so.
Might be wise to use ❗ at the start, similar to what's being done on [Windows Maintenance](https://rtech.support/docs/recommendations/maintenance.html#defrag)

2023-02-03 17:06 UTC, Tomat0r commented on docs/safety-security/disk-encryption.md
> +### It is not possible to Decrypt BitLocker without them and we will not asisst in doing so.
Will also move this to the top since it applies to every encryption method not only bitlocker

2023-02-03 17:27 UTC, Tomat0r approved these changes

2023-02-03 17:28 UTC, Tomat0r approved these changes

2023-02-03 21:04 UTC, Tomat0r approved these changes

2023-02-04 08:03 UTC, WhiteHusky commented on docs/safety-security/disk-encryption.md
> +- Not as widely used as other disk encryption software, meaning there may be less support and resources available
Though admittedly a footnote if anything. So perhaps the statement is still valid.

2023-02-05 14:41 UTC, WhiteHusky requested changes

2023-02-05 14:41 UTC, WhiteHusky commented on docs/networking/dns.md
> +The specific steps to change the DNS server in Linux depend on the distribution you are using. For most distributions, you can change the DNS server by editing the `/etc/resolv.conf` file and adding
Regarding [what was asked in the development channel](https://discord.com/channels/749314018837135390/1071069467955703888/1071760874135629835), it's a hard answer to ask on what's the most terse way to explain how to change the DNS that covers all the distros. We probably want people to stay within the GUI, so we could mention the few places where to find the settings in a couple common DEs (KDE, Gnome, Mate are a few that come to mind) and as a last resort suggest finding what [network manager](https://wiki.archlinux.org/index.php?title=Network_configuration&oldid=766537#Network_managers) their system is using then use that to modify DNS.

2023-02-05 14:47 UTC, WhiteHusky commented on docs/networking/dns.md
> +The specific steps to change the DNS server in Linux depend on the distribution you are using. For most distributions, you can change the DNS server by editing the `/etc/resolv.conf` file and adding
Though for desktop geared distros, it's almost always going to be `NetworkManager` that handles networking.

2023-02-08 17:29 UTC, Tomat0r approved these changes

2023-02-16 07:19 UTC, sealsrock12 approved these changes

2023-02-24 00:05 UTC, merged