Add files via upload
r-Techsupport/rTS_Wiki pull request #171
Opened 2023-02-27 11:41 UTC by Poodila

new bottlenecking article

2023-02-27 15:15 UTC, sealsrock12 commented on docs/learning/Bottlenecking.md
> +# BottleNecking
Is it Bottle necking, BottleNecking, or Bottlenecking? You should use one for everything.

2023-03-09 14:39 UTC, K97i requested changes

2023-03-09 14:39 UTC, K97i commented on docs/guides/OneDrive.md
> +2. Right-click (or CTRL-click in Mac) the OneDrive icon on the taskbar, Click the        ![settings](https://support.content.office.net/en-us/media/9c35458d-dc74-4d37-9cc7-89aff307eff9.png) icon and
You could upload the images under the assets folder in the main folder. Just remember to make your own folder for the specific article. If you want, you can add sub folders for each OS for your convenience.

2023-03-09 14:39 UTC, K97i commented on docs/learning/Bottlenecking.md
> +title: Bottle Necking
Like @sealsrock12 said, make sure your titles are **_actually consistent._**

2023-03-09 14:39 UTC, K97i commented on docs/learning/Bottlenecking.md
> +title: Bottle Necking
(use **Bottlenecking**)

2023-03-09 21:15 UTC, merged