WORK IN PROGRESS - Fixes #291
r-Techsupport/rTS_Wiki pull request #300
Opened 2024-06-24 01:57 UTC by Mr-KayZ

Work in progress to fix #291

TODO sections are marked for proper fix later. This PR is just to allow others to see my progress and make comments.

2024-07-01 02:13 UTC, Mr-KayZ commented
Potential remove images in email scams as they might be too obfuscated to be properly utilized

2024-07-01 10:32 UTC, Mr-KayZ commented
Add "Terminating sessions" in session hijack.md, include the following services for now:
- Discord
- Steam
- Epic Games
- Google
- Microsoft
Add others as necessary if others have more ideas

2024-07-01 14:55 UTC, PipeItToDevNull commented
Another image to add https://discord.com/channels/749314018837135390/749316166878625843/1257348587172528290

2024-07-01 14:57 UTC, PipeItToDevNull commented
https://discord.com/channels/749314018837135390/749316166878625843/1257349175885172806

2024-07-15 08:36 UTC, Mr-KayZ commented
Feel free to review and edit accordingly, or make comments, scams page complete!

2024-07-26 15:13 UTC, K97i requested changes
not a particularly deep proofread

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/email-scams.md
> +- A man received an email from a friend who is a software engineer. The email contained a suspicious link, which turned out to be a virus. The man confirmed with his friend that his email account had
```suggestion
- A man received an email from a friend who is a software engineer. The email contained a suspicious link, which turned out to be a virus. The man confirmed with his friend that his email account had been hacked. (See my personal example in [the "Example of a compromised account scam" section](/docs/safety-security/tech-scams.md) where I had fallen for one such scam message. While not email per say, the methodology works the same way.)
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/email-scams.md
> +These scams prey on your compassion, asking you to send money to help victims of various causes. Check CharityWatch to verify unfamiliar charities.
```suggestion
These scams prey on your compassion, asking you to send money to help victims of various causes. Check [CharityWatch](https://www.charitywatch.org/) to verify unfamiliar charities.
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/session-hijack.md
> +Session hijacking is a cyber attack where an attacker intercepts and controls a user's session with a web application. This can occur during various online activities, such as checking credit card ba
```suggestion
Session hijacking is a cyberattack where an attacker intercepts and controls a user's session with a web application. This can occur during various online activities, such as checking credit card balances or shopping. The attacker can then perform any action that the legitimate user could, leading to potential consequences, like accessing sensitive information, stealing money, or committing identity theft. 
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/session-hijack.md
> +Passive session hijacking occurs when an attacker eavesdrops on network traffic to steal the target’s session ID. This type of attack is easier to execute because all an attacker needs is access to n
```suggestion
Passive session hijacking occurs when an attacker eavesdrops on network traffic to steal the target’s session ID. This type of attack is easier to execute because all an attacker needs is access to network traffic, which can be easily accomplished if they are on the same network as the target. This is why it is recommended to be extra careful especially when utilizing public Wi-Fi for places, such as coffee shops and airports.
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/session-hijack.md
> +However, cookies can also pose security and privacy concerns. Some viruses and malware may be disguised as cookies. These malicious elements can be used to facilitate session hijacking, a type of cyb
```suggestion
However, cookies can also pose security and privacy concerns. Some viruses and malware may be disguised as cookies. These malicious elements can be used to facilitate session hijacking, a type of cyberattack where an attacker intercepts and takes control of a user’s session with a web application. This can be done actively, where the attacker takes control of the target’s session while it’s active, or passively, where the attacker eavesdrops on network traffic to steal the target’s session ID (Or session token).
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/session-hijack.md
> +- **Online Shopping Platforms (Amazon, eBay, etc.)**: These sites have your financial information, making them attractive targets. Always ensure you're using a secure (https) connection and log out w
```suggestion
- **Online Shopping Platforms (Amazon, eBay, etc.)**: These sites have your financial information, making them attractive targets. Always ensure you're using a secure (HTTPS) connection and log out when finished.
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/session-hijack.md
> +Remember, the key to protecting yourself is vigilance. Always be aware of the information you're sharing and who you're sharing it with. Use all available security measures, such as strong, unique pa
```suggestion
Remember, the key to protecting yourself is vigilance. Always be aware of the information you're sharing and who you're sharing it with. Use all available security measures, such as strong, unique passwords, two-factor authentication, and secure (HTTPS) connections.
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/session-hijack.md
> +If it was hijacked fully and there are no viable means of recovering your account (See: [Account recovery self help page](https://help.steampowered.com/en/wizard/HelpWithLogin) of Steam), you may nee
```suggestion
If it was hijacked fully and there are no viable means of recovering your account (See: [Account recovery self-help page](https://help.steampowered.com/en/wizard/HelpWithLogin) of Steam), you may need to contact [Steam Support directly](https://help.steampowered.com/en/wizard/HelpWithAccount) and create a ticket there to validate yourself.
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/session-hijack.md
> +If it was hijacked fully and there are no viable means of recovering your account, (See: [Account recovery self help page](https://www.epicgames.com/help/en-US/c-Category_EpicAccount/c-AccountSecurit
```suggestion
If it was hijacked fully and there are no viable means of recovering your account, (See: [Account recovery self-help page](https://www.epicgames.com/help/en-US/c-Category_EpicAccount/c-AccountSecurity/my-epic-account-was-compromised-and-i-cannot-access-it-a000085846) of Epic Games), you may need to contact [Epic Games directly](https://www.epicgames.com/help/en-US/c-Category_TechnicalSupport/c-TechnicalSupport_GeneralSupport/how-do-i-submit-an-epic-games-support-request-if-i-can-t-log-in-to-my-account-a000088916) via the link and follow their instructions which will work even if you cannot log into any account.
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/tech-scams.md
> +This document is to provided you with details on the methods people use to take advantage of the unknowing and what they use to get people to trust them. This document will go into some of the forms
```suggestion
This page will go into how people take advantage of the unknowing, what methods they use to gain the trust of people, and what you can do if you already fell to their scam to hopefully recuperate your compromised information and accounts.
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/tech-scams.md
> +### Example of a compromized account scam
```suggestion
### Example of a compromised account scam
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/tech-scams.md
> +    _An example of one of these compromized account scams can be found by clicking here._
```suggestion
    _An example of one of these compromised account scams can be found by clicking here._
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/tech-scams.md
> +Keeping your operating system and web browser updated is a key aspect of maintaining system security. Software updates often include patches for known vulnerabilities, which can significantly reduce
```suggestion
Keeping your operating system and web browser updated is a key aspect of maintaining system security. Software updates often include patches for known vulnerabilities, which can significantly reduce the risk of a successful cyberattack. An updated system is less susceptible to malicious code execution, providing a safer environment for your online activities.
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/tech-scams.md
> +- [Steamguard](https://help.steampowered.com/en/faqs/view/06B0-26E6-2CF8-254C) (For Steam only)
```suggestion
- [Steam Guard](https://help.steampowered.com/en/faqs/view/06B0-26E6-2CF8-254C) (For Steam only)
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/tech-scams.md
> +Using [password managers](/docs/safety-security/pw-managers) is also another extra safety precaution we highly recommend to ensure you use different passwords on different accounts. Using the same pa
```suggestion
Using [password managers](/docs/safety-security/pw-managers) is also another extra safety precaution we highly recommend ensuring you use different passwords on different accounts. Using the same password for multiple accounts is bad practice and can lead the attackers to access other accounts on other services.
```

2024-07-26 15:13 UTC, K97i commented on docs/safety-security/tech-scams.md
> +The first step is to reset password and terminate sessions from said accounts. Steps to do so, including how to terminate sessions from common services and applications can be found [here](/docs/safe
```suggestion
The first step is to reset passwords and terminate sessions from said accounts. You can learn how to do so, including how to terminate sessions from common services and applications can be found, [here](/docs/safety-security/session-hijack#terminating-sessions-from-services).
```

2024-08-08 17:50 UTC, Mr-KayZ commented
Refer to this message here to see how to fix it later: https://discord.com/channels/749314018837135390/1071069467955703888/1266453384769179731

2025-01-26 06:40 UTC, closed without merging