updated win11 bypasses
r-Techsupport/rTS_Wiki pull request #304
Opened 2024-06-28 03:57 UTC by back-lacking

2024-06-28 12:25 UTC, PipeItToDevNull commented on docs/guides/bypass-11.md
> +## Bypassing network requirements
Capitalization of sections is inconsistent on this page, I believe this method of not capitalizing every word is typically what we use in the Wiki

2024-06-28 12:27 UTC, PipeItToDevNull commented on docs/installations/install-11.md
> +If you need to setup Windows 11 without an internet connection or without a Microsoft account, follow this [article](/docs/guides/bypass-11.md).
Can we do a section header above this, like in the LLCD article. Not sure what to call it though, maybe "## Advanced setup guides"

2024-06-28 21:29 UTC, PipeItToDevNull commented
Looks good to me, @TheKrol or @sealsrock12

2024-06-28 21:29 UTC, PipeItToDevNull commented
this would close #303

2024-07-02 00:33 UTC, TheKrol requested changes

2024-07-02 00:33 UTC, TheKrol commented on docs/installations/install-11.md
> +If you need to setup Windows 11 without an internet connection or without a Microsoft account, follow this [article](/docs/guides/bypass-11.md).
Need to change without an ending to match other parts of the wiki, otherwise it doesn't work.

2024-07-02 00:33 UTC, TheKrol commented on docs/installations/install-11.md
>  You have successfully installed Windows 11.
Should probably remove the article before this, and but the "You have successfully installed Windows 11" Under the post -install guide

2024-07-02 01:31 UTC, merged